version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "GalvinPython"
    target-branch: "dev"

  - package-ecosystem: "bun"
    directory: "/web"
    schedule:
      interval: "weekly"
    assignees:
      - "GalvinPython"
    target-branch: "dev"
    labels: ["dependencies", "javascript", "component: web"]

  - package-ecosystem: "cargo"
    directory: "/api"
    schedule:
      interval: "weekly"